language: scala
jdk: oraclejdk8
scala:
- 2.11.5
before_install:
- openssl aes-256-cbc -K $encrypted_8b016fa5759f_key -iv $encrypted_8b016fa5759f_iv -in key.pem.enc -out /tmp/key.pem -d
script:
- sbt publish
- sudo chmod 600 /tmp/key.pem
- ssh -o StrictHostKeyChecking=no ubuntu@52.11.177.152 -i /tmp/key.pem sh run_command.sh

